# Generated by Django 4.2.3 on 2025-10-19 04:08

import django.contrib.auth.models
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelManagers(
            name="user",
            managers=[
                ("objects", django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.AddField(
            model_name="user",
            name="google_id",
            field=models.CharField(blank=True, max_length=255, null=True, unique=True, verbose_name="Google ID"),
        ),
        migrations.AlterField(
            model_name="user",
            name="date_joined",
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name="date joined"),
        ),
        migrations.AlterField(
            model_name="user",
            name="verified",
            field=models.BooleanField(default=True, verbose_name="Email Verified"),
        ),
    ]
