# Generated by Django 5.2.7 on 2025-10-18 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BulkUpload',
            fields=[
                ('upload_id', models.AutoField(db_column='uploadId', primary_key=True, serialize=False)),
                ('s3_link', models.URLField(db_column='s3Link', verbose_name='S3 Link')),
                ('status', models.CharField(choices=[('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed')], default='processing', max_length=20, verbose_name='Status')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
            ],
            options={
                'verbose_name': 'Bulk Upload',
                'verbose_name_plural': 'Bulk Uploads',
                'db_table': 'bulk_uploads',
            },
        ),
        migrations.CreateModel(
            name='Invite',
            fields=[
                ('invite_id', models.AutoField(db_column='inviteId', primary_key=True, serialize=False)),
                ('invitee_email', models.EmailField(max_length=254, verbose_name='Invitee Email')),
                ('can_view', models.BooleanField(default=False, verbose_name='Can View')),
                ('can_admin', models.BooleanField(default=False, verbose_name='Can Admin')),
                ('can_update', models.BooleanField(default=False, verbose_name='Can Update')),
                ('used', models.BooleanField(default=False, verbose_name='Used')),
                ('secret', models.CharField(max_length=255, unique=True, verbose_name='Secret')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('expires_at', models.DateTimeField(verbose_name='Expires At')),
            ],
            options={
                'verbose_name': 'Invite',
                'verbose_name_plural': 'Invites',
                'db_table': 'invites',
            },
        ),
        migrations.CreateModel(
            name='Namespace',
            fields=[
                ('namespace_id', models.AutoField(db_column='namespaceId', primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255, unique=True, verbose_name='Namespace Name')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
            ],
            options={
                'verbose_name': 'Namespace',
                'verbose_name_plural': 'Namespaces',
                'db_table': 'namespaces',
            },
        ),
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('org_id', models.AutoField(db_column='orgId', primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255, verbose_name='Organization Name')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
            ],
            options={
                'verbose_name': 'Organization',
                'verbose_name_plural': 'Organizations',
                'db_table': 'organizations',
            },
        ),
        migrations.CreateModel(
            name='OrganizationMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('can_view', models.BooleanField(default=False, verbose_name='Can View')),
                ('can_admin', models.BooleanField(default=False, verbose_name='Can Admin')),
                ('can_update', models.BooleanField(default=False, verbose_name='Can Update')),
                ('joined_at', models.DateTimeField(auto_now_add=True, verbose_name='Joined At')),
            ],
            options={
                'verbose_name': 'Organization Member',
                'verbose_name_plural': 'Organization Members',
                'db_table': 'organization_members',
            },
        ),
    ]
