# Generated by Django 5.2.7 on 2025-10-18 12:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('organizations', '0001_initial'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='bulkupload',
            name='user',
            field=models.ForeignKey(db_column='userId', on_delete=django.db.models.deletion.CASCADE, related_name='bulk_uploads', to='users.User'),
        ),
        migrations.AddField(
            model_name='invite',
            name='inviter',
            field=models.ForeignKey(db_column='inviter_userId', on_delete=django.db.models.deletion.CASCADE, related_name='sent_invites', to='users.User'),
        ),
        migrations.AddField(
            model_name='namespace',
            name='created_by',
            field=models.ForeignKey(db_column='createdByUserId', on_delete=django.db.models.deletion.CASCADE, related_name='created_namespaces', to='users.User'),
        ),
        migrations.AddField(
            model_name='bulkupload',
            name='namespace',
            field=models.ForeignKey(db_column='namespaceId', on_delete=django.db.models.deletion.CASCADE, related_name='bulk_uploads', to='organizations.namespace'),
        ),
        migrations.AddField(
            model_name='organization',
            name='owner',
            field=models.ForeignKey(db_column='ownerId', on_delete=django.db.models.deletion.CASCADE, related_name='owned_organizations', to='users.User'),
        ),
        migrations.AddField(
            model_name='namespace',
            name='organization',
            field=models.ForeignKey(db_column='orgId', on_delete=django.db.models.deletion.CASCADE, related_name='namespaces', to='organizations.organization'),
        ),
        migrations.AddField(
            model_name='invite',
            name='organization',
            field=models.ForeignKey(db_column='orgId', on_delete=django.db.models.deletion.CASCADE, related_name='invites', to='organizations.organization'),
        ),
        migrations.AddField(
            model_name='bulkupload',
            name='organization',
            field=models.ForeignKey(db_column='orgId', on_delete=django.db.models.deletion.CASCADE, related_name='bulk_uploads', to='organizations.organization'),
        ),
        migrations.AddField(
            model_name='organizationmember',
            name='organization',
            field=models.ForeignKey(db_column='orgId', on_delete=django.db.models.deletion.CASCADE, related_name='members', to='organizations.organization'),
        ),
        migrations.AddField(
            model_name='organizationmember',
            name='user',
            field=models.ForeignKey(db_column='userId', on_delete=django.db.models.deletion.CASCADE, related_name='organization_memberships', to='users.User'),
        ),
        migrations.AlterUniqueTogether(
            name='organizationmember',
            unique_together={('organization', 'user')},
        ),
    ]
