# Generated by Django 4.2.3 on 2025-10-18 17:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("namespaces", "0001_initial"),
        ("organizations", "0002_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="bulkupload",
            name="namespace",
            field=models.ForeignKey(
                db_column="namespaceId",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="bulk_uploads",
                to="namespaces.namespace",
            ),
        ),
        migrations.DeleteModel(
            name="Namespace",
        ),
    ]
