# Generated by Django 4.2.3 on 2025-10-19 02:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):
    dependencies = [
        ("namespaces", "0002_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("organizations", "0002_create_organization_member"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="organization",
            name="description",
        ),
        migrations.AlterField(
            model_name="organization",
            name="org_id",
            field=models.UUIDField(
                db_column="orgId", default=uuid.uuid4, editable=False, primary_key=True, serialize=False
            ),
        ),
        migrations.AlterField(
            model_name="organization",
            name="owner",
            field=models.ForeignKey(
                db_column="ownerId",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="owned_organizations",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.CreateModel(
            name="Invite",
            fields=[
                (
                    "invite_id",
                    models.UUIDField(
                        db_column="inviteId", default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("invitee_email", models.EmailField(max_length=254, verbose_name="Invitee Email")),
                (
                    "role",
                    models.CharField(
                        choices=[("viewer", "Viewer"), ("editor", "Editor"), ("admin", "Admin")],
                        default="viewer",
                        help_text="Role the invitee will have in the organization",
                        max_length=20,
                        verbose_name="Role",
                    ),
                ),
                ("used", models.BooleanField(default=False, verbose_name="Used")),
                ("secret", models.CharField(max_length=255, unique=True, verbose_name="Secret")),
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="Created At")),
                ("expires_at", models.DateTimeField(verbose_name="Expires At")),
                (
                    "inviter",
                    models.ForeignKey(
                        db_column="inviter_userId",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sent_invites",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        db_column="orgId",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="invites",
                        to="organizations.organization",
                    ),
                ),
            ],
            options={
                "verbose_name": "Invite",
                "verbose_name_plural": "Invites",
                "db_table": "invites",
            },
        ),
        migrations.CreateModel(
            name="BulkUpload",
            fields=[
                (
                    "upload_id",
                    models.UUIDField(
                        db_column="uploadId", default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("s3_link", models.URLField(db_column="s3Link", verbose_name="S3 Link")),
                (
                    "status",
                    models.CharField(
                        choices=[("processing", "Processing"), ("completed", "Completed"), ("failed", "Failed")],
                        default="processing",
                        max_length=20,
                        verbose_name="Status",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="Created At")),
                (
                    "namespace",
                    models.ForeignKey(
                        db_column="namespaceId",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="bulk_uploads",
                        to="namespaces.namespace",
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        db_column="orgId",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="bulk_uploads",
                        to="organizations.organization",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        db_column="userId",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="bulk_uploads",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Bulk Upload",
                "verbose_name_plural": "Bulk Uploads",
                "db_table": "bulk_uploads",
            },
        ),
    ]
