# Generated by Django 4.2.3 on 2025-10-18 18:50

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("organizations", "0003_alter_bulkupload_namespace_delete_namespace"),
    ]

    operations = []
