# Generated by Django 4.2.3 on 2025-10-18 19:19

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):
    dependencies = [
        ("organizations", "0007_add_invitations"),
    ]

    operations = [
        migrations.AlterField(
            model_name="bulkupload",
            name="upload_id",
            field=models.UUIDField(
                db_column="uploadId", default=uuid.uuid4, editable=False, primary_key=True, serialize=False
            ),
        ),
        migrations.AlterField(
            model_name="invite",
            name="invite_id",
            field=models.UUIDField(
                db_column="inviteId", default=uuid.uuid4, editable=False, primary_key=True, serialize=False
            ),
        ),
        migrations.AlterField(
            model_name="organization",
            name="org_id",
            field=models.UUIDField(
                db_column="orgId", default=uuid.uuid4, editable=False, primary_key=True, serialize=False
            ),
        ),
        migrations.DeleteModel(
            name="OrganizationInvitation",
        ),
    ]
