# Generated by Django 4.2.3 on 2025-10-18 17:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("organizations", "0002_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Namespace",
            fields=[
                ("namespace_id", models.AutoField(db_column="namespaceId", primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=255, unique=True, verbose_name="Namespace Name")),
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="Created At")),
                (
                    "created_by",
                    models.ForeignKey(
                        db_column="createdByUserId",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="created_namespaces",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        db_column="orgId",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="namespaces",
                        to="organizations.organization",
                    ),
                ),
            ],
            options={
                "verbose_name": "Namespace",
                "verbose_name_plural": "Namespaces",
                "db_table": "namespaces",
            },
        ),
    ]
