# Generated by Django 4.2.3 on 2025-10-18 22:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Namespace",
            fields=[
                (
                    "namespace_id",
                    models.UUIDField(
                        db_column="namespaceId", default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("name", models.CharField(max_length=255, unique=True, verbose_name="Namespace Name")),
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="Created At")),
                (
                    "created_by",
                    models.ForeignKey(
                        db_column="createdByUserId",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="created_namespaces",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Namespace",
                "verbose_name_plural": "Namespaces",
                "db_table": "namespaces",
            },
        ),
    ]
