# Generated by Django 4.2.3 on 2025-10-18 22:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("namespaces", "0001_initial"),
        ("organizations", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="namespace",
            name="organization",
            field=models.ForeignKey(
                db_column="orgId",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="namespaces",
                to="organizations.organization",
            ),
        ),
    ]
