# Generated by Django 4.2.3 on 2025-10-18 19:19

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):
    dependencies = [
        ("namespaces", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="namespace",
            name="namespace_id",
            field=models.UUIDField(
                db_column="namespaceId", default=uuid.uuid4, editable=False, primary_key=True, serialize=False
            ),
        ),
    ]
